### ISSUE TITLE
Support for parsing opts line in /proc/self/mountstats

### ISSUE THREAD

**Issue by arsenakishev** [prometheus/procfs#102]
Currently procfs does not support parsing of the ```opts:``` line in proc/self/mountstats. Having these values would give users access to more info related to their mounts. This would also help with resolving an issue with node_exporter (https://github.com/prometheus/node_exporter/issues/993) where different versions of nfs would not be recognized thus causing only a single form of metrics to show.

**Comment by SuperQ** [comment]
It would also be nice to have this info for a `node_mountstats_info` metric. The only difficult is there seems to be some variation in available fields, so we would have to parse all mountstats, normalize the list of fields, and then fill in with empty string for mounts that have missing fields.

**Comment by brian-brazil** [comment]
client_golang has changed so that's no longer required.

**Comment by arsenakishev** [comment]
@brian-brazil Did you mean that parsing of opts is no longer required or something else? Just looking for some clarification.

**Comment by discordianfish** [comment]
Not sure what @brian-brazil is refering to.
In general +1 on this. Is this "accepted"? As in are we willing to accept a PR to implement this?

**Comment by brian-brazil** [comment]
>  The only difficult is there seems to be some variation in available fields, so we would have to parse all mountstats, normalize the list of fields, and then fill in with empty string for mounts that have missing fields.

Is what I was referring to.

**Comment by discordianfish** [comment]
Got it, thanks. Either way, from the procfs pov this doesn't matter. So let's add this?
