### ISSUE TITLE
Commit 185b42884 breaks builds on Linux

### ISSUE THREAD

**Issue by abourget** [prometheus/procfs#116]
Because of a redeclaration of `SysReadFile` in the new `sysreadfile_linux.go` (redefined from `parse.go`).

Commit: 185b4288413d2a0dd0806f78c90dde719829e5ae

**Comment by beorn7** [comment]
But in that same commit, `SysReadFile` is removed from `parse.go`, isn't it?

**Comment by pgier** [comment]
I'm not able to reproduce this, I'm guessing it was due to some local files which were modified or out of date.

**Comment by SuperQ** [comment]
Yes, this sounds like bad vendoring or broken checkout.
