### ISSUE TITLE
Add pressure stall information

### ISSUE THREAD

**Issue by daenney** [prometheus/procfs#126]
I'd like to add support for `/proc/pressure/*` that the Linux kernel exposes (to in turn add support for that to the node exporter).

I started looking at it but I'm stumbling on a thing; currently `Proc` and its `path` helper always assumes that what we want is `/proc/<pid>/<path...>` however what I need access to is `/proc/pressure/{cpu,memory,io}` and I can't seem to find a good way to do that.

Did I miss something in the `Proc` API or should I just read the contents of those three files without leveraging the `Proc` struct and its methods?

**Comment by SuperQ** [comment]
Related: https://github.com/prometheus/node_exporter/issues/1174

You're probably looking to implement something similar to one of the other handlers like [/proc/net/dev](https://github.com/prometheus/procfs/blob/master/net_dev.go#L60-L63).
