### ISSUE TITLE
Checksum mismatch during install of procfs

### ISSUE THREAD

**Issue by kcameron1973** [prometheus/procfs#129]
While trying to install this package on its own or as part of the blackbox_exporter "make" getting a failure verifying download:

[kcameron@kevlar1 blackbox_exporter-master]$ sudo go install "github.com/prometheus/procfs"
go: downloading github.com/prometheus/procfs v0.0.0-20170703101242-e645f4e5aaa8
go: verifying github.com/prometheus/procfs@v0.0.0-20170703101242-e645f4e5aaa8: checksum mismatch
        downloaded: h1:uZfczEBIA1FZfOQo4/JWgGnMNd/4HVsM9A+B30wtlkA=
        go.sum:     h1:Kh7M6mzRpQ2de1rixoSQZr4BTINXFm8WDbeN5ttnwyE=

Also noted in: https://groups.google.com/forum/?utm_source=digest&utm_medium=email/#!topic/prometheus-users/98Q-q_2OlW0

**Comment by discordianfish** [comment]
See the answer on the mailing list. Just tried and can't reproduce. This looks like the described problem with the mod cache (try running `go clean -modcache`)
