### ISSUE TITLE
Test don't pass on OSX 10.10.5

### ISSUE THREAD

**Issue by hydroflame** [prometheus/procfs#13]
--- FAIL: TestSelf (0.00s)
    	proc_test.go:13: could not read /proc: stat /proc: no such file or directory
    --- FAIL: TestFileDescriptors (0.00s)
    	proc_test.go:102: could not read /proc: stat /proc: no such file or directory
    --- FAIL: TestFileDescriptorTargets (0.00s)
    	proc_test.go:149: could not read /proc: stat /proc: no such file or directory
    FAIL
    FAIL	github.comcast.com/vbo/derp-4/vendor/github.com/prometheus/procfs	0.013s

**Comment by grobie** [comment]
OSX/darwin does not have a procfs, that's why these tests fail. I guess the point can be made that this dependency is not strictly necessary for tests, so I removed it in #14.
