### ISSUE TITLE
Add support for parsing smaps

### ISSUE THREAD

**Issue by SuperQ** [prometheus/procfs#139]
We're looking into memory usage of some ruby code, and we discovered some interesting information about getting more "real" memory use for processes based on `/proc/<pid>/smaps`.

It would be interesting to get similar set of data for a PSS size in client_golang.

See:
* https://gitlab.com/gitlab-org/gitlab-monitor/merge_requests/80
* https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3858#note_118105718

**Comment by binjip978** [comment]
Probably this commit https://github.com/prometheus/procfs/commit/9654394ca94a53f3922b7322a923863f9558d399 address this issue pretty well, or something else need to be done?

**Comment by discordianfish** [comment]
Yes, looks like this can be closed.
