### ISSUE TITLE
Support for /proc/sys/vm

### ISSUE THREAD

**Issue by stevenjm** [prometheus/procfs#157]
Hi,

I raised the suggestion of having the node exporter expose metrics from `/proc/sys/vm` [on the mailing list](https://groups.google.com/forum/?fromgroups#!topic/prometheus-developers/iXzsjy0NFAE) and was suggested to raise an issue here.

For my specific use case, exposing `/proc/sys/vm/max_map_count` is sufficient. There are also other files in `/proc/sys/vm` that we might consider exposing.

I'm happy to work on coding this once there's consensus on the approach.

Regards,
Steven

**Comment by pgier** [comment]
@stevenjm Feel free to submit a PR for this.  This can probably be implemented similarly to some of the functions in the `sysfs` package, which also reads a lot of small files with one value each.

**Comment by TheMeier** [comment]
I'd like to take that one.
