### ISSUE TITLE
Build failed when using both prometheus/node_exporter and prometheus/client_golang

### ISSUE THREAD

**Issue by cuonglm** [prometheus/procfs#175]
I have a simple program:

```
package main

import (
	"github.com/prometheus/client_golang/prometheus/push"
	"github.com/prometheus/node_exporter/collector"
)

func main() {
	nc, err := collector.NewNodeCollector()
	if err != nil {
		panic(err)
	}
	pusher := push.New("http://localhost/metrics", "test")
	for _, c := range nc.Collectors {
		pusher.Collector(c)
	}
}
```

Run it with go module enabled:

```
$ GO111MODULE=on go1.12.5 run main.go
go: finding github.com/prometheus/node_exporter/collector latest
go: finding github.com/prometheus/client_golang/prometheus/push latest
go: finding github.com/prometheus/client_golang/prometheus latest
# github.com/prometheus/node_exporter/collector
/home/cuonglm/go/pkg/mod/github.com/prometheus/node_exporter@v0.18.1/collector/buddyinfo.go:58:24: c.fs.NewBuddyInfo undefined (type procfs.FS has no field or method NewBuddyInfo)
/home/cuonglm/go/pkg/mod/github.com/prometheus/node_exporter@v0.18.1/collector/cpufreq_linux.go:83:23: c.fs.NewSystemCpufreq undefined (type sysfs.FS has no field or method NewSystemCpufreq)
/home/cuonglm/go/pkg/mod/github.com/prometheus/node_exporter@v0.18.1/collector/ipvs_linux.go:109:24: c.fs.NewIPVSStats undefined (type procfs.FS has no field or method NewIPVSStats)
/home/cuonglm/go/pkg/mod/github.com/prometheus/node_exporter@v0.18.1/collector/ipvs_linux.go:124:27: c.fs.NewIPVSBackendStatus undefined (type procfs.FS has no field or method NewIPVSBackendStatus)
/home/cuonglm/go/pkg/mod/github.com/prometheus/node_exporter@v0.18.1/collector/netclass_linux.go:172:23: c.fs.NewNetClass undefined (type sysfs.FS has no field or method NewNetClass)
```

The problem is `prometheus/node_exporter` and `prometheus/client_golang` requires 2 version of procfs, which are conflicts with each other.

The graph shows the version `github.com/prometheus/procfs@v0.0.2 golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4` was chosen. The commit https://github.com/prometheus/procfs/commit/65bdadfa96aecebf4dcf888da995a29eab4fc964 (requires by node_exporter) is behind the commit https://github.com/prometheus/procfs/commit/833678b5bb319f2d20a475cb165c6cc59c2cc77c (v0.0.2).

In any case, I think the main problem is from `procfs` itself, as some public APIs were removed in commit https://github.com/prometheus/procfs/commit/985b82318ecc7741179e9c11a99095cd1f6965c9

The better idea is intoducing new public APIs and mark the old one as deprecated.

**Comment by dswarbrick** [comment]
I was also caught out by this, whilst trying to update Debian's packaging for prometheus-node-exporter. Version 0.18.0 seems to require a pre-0.0.1 git snapshot of procfs, whilst version 0.18.1 requires _exactly_ version 0.0.1 of procfs. Anything later than that (0.0.2+) breaks the build due to the removal of these top-level functions:
```
src/github.com/prometheus/node_exporter/collector/buddyinfo.go:58:24: c.fs.NewBuddyInfo undefined (type procfs.FS has no field or method NewBuddyInfo) src/github.com/prometheus/node_exporter/collector/cpufreq_linux.go:83:23: c.fs.NewSystemCpufreq undefined (type sysfs.FS has no field or method NewSystemCpufreq) src/github.com/prometheus/node_exporter/collector/ipvs_linux.go:109:24: c.fs.NewIPVSStats undefined (type procfs.FS has no field or method NewIPVSStats) src/github.com/prometheus/node_exporter/collector/ipvs_linux.go:124:27: c.fs.NewIPVSBackendStatus undefined (type procfs.FS has no field or method NewIPVSBackendStatus) src/github.com/prometheus/node_exporter/collector/netclass_linux.go:172:23: c.fs.NewNetClass undefined (type sysfs.FS has no field or method NewNetClass)
```

**Comment by cuonglm** [comment]
cc @pgier @discordianfish

**Comment by SuperQ** [comment]
@dswarbrick I had to bump the procfs slightly in node_exporter 0.18.1 to fix a parsing bug.

**Comment by dswarbrick** [comment]
@SuperQ Thanks for the info. Will node_exporter be releasing a new version that builds against procfs 0.0.2, or will procfs re-add some top level function wrappers like they did in #170 ?

**Comment by SuperQ** [comment]
We'll probably update the node_exporter master to work with the latest procfs version sometime soon. A new release depends on what features we're working.

**Comment by cuonglm** [comment]
@SuperQ Update node_exporter should work, but it's likely that there're user out there which rely on removed methods.

The best way to fix this is in procfs, but re-adding removed methods and mark them as deprecated. If not, the changelog should be updated to insist the in-compatible change.
