### ISSUE TITLE
*: remove non-test uses of reflect

### ISSUE THREAD

**Issue by mdlayher** [prometheus/procfs#177]
As mentioned in a couple of issues, IMHO the use of reflection is not justified in order to save a few keystrokes. The data coming from proc/sysfs files is not truly dynamic: there are known file names with values that can be mapped to known fields. This type of code can be easily rewritten using a switch statement. When implementing something like a JSON decoder that may have to handle truly arbitrary data, the use of reflection is much more justified.

The use of reflection throws away many of the compile time checks we take for granted, and two of the Go proverbs come to mind: "Clear is better than clever. Reflection is never clear."

https://go-proverbs.github.io/

Therefore, I suggest we remove all uses of reflection from the non-test code in these packages, and do not allow any new code that uses reflection.

```
$ grep -r "reflect" | grep -v "_test"
sysfs/net_class.go:     "reflect"
sysfs/net_class.go:     interfaceElem := reflect.ValueOf(&interfaceClass).Elem()
sysfs/net_class.go:     interfaceType := reflect.TypeOf(interfaceClass)
sysfs/net_class.go:             case reflect.String:
sysfs/net_class.go:             case reflect.Ptr:
sysfs/net_class.go:                     case reflect.TypeOf(int64ptr):
sysfs/net_class.go:                             fieldValue.Set(reflect.ValueOf(&intValue))
sysfs/class_power_supply.go:    "reflect"
sysfs/class_power_supply.go:    powerSupplyElem := reflect.ValueOf(&powerSupply).Elem()
sysfs/class_power_supply.go:    powerSupplyType := reflect.TypeOf(powerSupply)
sysfs/class_power_supply.go:            case reflect.String:
sysfs/class_power_supply.go:            case reflect.Ptr:
sysfs/class_power_supply.go:                    case reflect.TypeOf(int64ptr):
sysfs/class_power_supply.go:                            fieldValue.Set(reflect.ValueOf(&intValue))
```

**Comment by mdlayher** [comment]
I will give https://github.com/prometheus/procfs/blob/master/sysfs/class_power_supply.go a try and then post a PR.

**Comment by TheMeier** [comment]
@mdlayher did you already work on `sysfs/net_class.go` I could clean that up ...

**Comment by discordianfish** [comment]
@TheMeier I don't think he does, so feel free to submit a PR! :)
