### ISSUE TITLE
Create/document recommendation for file io best practices

### ISSUE THREAD

**Issue by pgier** [prometheus/procfs#188]
We currently have a mix of some functions using `ioutil.ReadFile` and others using a scanner to read line by line.  Given that some files in procfs change frequently and are not guaranteed to be consistent between successive reads (https://stackoverflow.com/questions/5713451/is-it-safe-to-parse-a-proc-file), should we favor reading a full files and then parsing the data afterwards instead of using a scanner to read line-by-line?

**Comment by SuperQ** [comment]
None of the files we read are extremely large. Deprecating scanner and moving to single read calls seems like the best option to me.

**Comment by discordianfish** [comment]
Makes sense!

**Comment by pgier** [comment]
Closing this, since I think there is nothing else to do for now.
