### ISSUE TITLE
Add support for parsing cgroup

### ISSUE THREAD

**Issue by mmailhos** [prometheus/procfs#201]
We've encountered a case where we needed to know wether a particular process was running inside a container or not. One way to achieve this is to check for cgroups inheritance from the container runtime via `/proc/<pid>/cgroup`.

It would be great to have visibility on the hierarchical dependencies per cgroup resource controller.

**Comment by hamiltont** [comment]
Happy to take this one on. I already have a bit of related code+tests from [my work on systemd-exporter](https://github.com/hamiltont/systemd_exporter/tree/feat/add-circleci/cgroup) that I was hoping to upstream. I may need some help with building the best possible API in go, so if anyone would be willing to act as a sounding board please comment here and I will tag you when there is a specific code question. (As an example - cgroups v1 and v2 APIs differ. Should we try to expose one master cgroups API, or two specific APIs?)

At the least, I can at least knock out the bulk of 'setup the fixtures, parse files into structs' boilerplate to get this moving
