### ISSUE TITLE
Add parsing of /proc/flashcache

### ISSUE THREAD

**Issue by SuperQ** [prometheus/procfs#218]
In addition to bcache, there is [flashcache](https://github.com/facebookarchive/flashcache/blob/master/doc/flashcache-sa-guide.txt). It would be useful to have parsing of this for the node_exporter.

**Comment by bisakhmondal** [comment]
Hii @SuperQ, I'd love to work on this issue. Could you please guide me? Thanks.

**Comment by SuperQ** [comment]
Sure, do you have a device that is using flashcache? For example, QNAP NAS devices?

If you don't, I can post some example data here. If you look at `meminfo.go`, you can see a general style for parsing the kind of files provided.

**Comment by bisakhmondal** [comment]
Thanks @SuperQ for the reply. Sadly I don't have any such devices. Please do share some data.
Now I have got a fairly good idea about flash cache. So ultimately we have to just parse it, right?

**Comment by SuperQ** [comment]
For procfs, it's a reasonably simple "parse the data and map it one-to-one with a struct".

I've added a PR with an example set of fixtures for you to test against.

**Comment by bisakhmondal** [comment]
Thanks for the fixtures. I'll open a PR when it's done.

**Comment by SuperQ** [comment]
Going to close this, the facebook patches are abandoned and never went into mainline. There's really no point in supporting this.
