### ISSUE TITLE
Parsing hypen in mountinfo incorrect

### ISSUE THREAD

**Issue by meriororen** [prometheus/procfs#225]
Hello,

Sometimes other field (like mount points) can have hyphen in them, causing mountinfo parser to put wrong information in wrong field. 

I do think this line
https://github.com/prometheus/procfs/blob/master/mountinfo.go#L93

can be improved. 

In my case, my usb drive mount point is, /media/isa/300A-6F09, this could cause incorrect optional field separation.

**Comment by SuperQ** [comment]
Yup, there are other cases where this is broken. We also want to eliminate the use of buffio scanners, so I think a bit of a re-write is in order. It might be worth making this a regexp parser.
