### ISSUE TITLE
Does not work with partitions that have a "-" in their name

### ISSUE THREAD

**Issue by probonopd** [prometheus/procfs#227]
Does not work with partitions that have a "-" in their name, as is relatively common e.g, for disks that have been automatically named by the system. 

`/proc/self/mountinfo` entry

```
363 28 8:1 / /media/neon/DEBB-1E3A rw,nosuid,nodev,relatime shared:228 - vfat /dev/sda1 rw,uid=999,gid=999,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro
```

gets incorrectly parsed to `/media/neon/DEBB`.

I think the logic error is in

https://github.com/prometheus/procfs/blob/8fcc02dcd366318084a9576bfeee615c7191ae6a/mountinfo.go#L86-L101

because "-" is not the separator, " - " is.

**Comment by discordianfish** [comment]
Dup of #225
