### ISSUE TITLE
Add support for parsing meminfo

### ISSUE THREAD

**Issue by bradbeam** [prometheus/procfs#230]
Would be great to have support for /proc/meminfo. 
I see https://github.com/prometheus/procfs/pull/18 from a few years ago. Is this a good enough base to start with?

**Comment by pgier** [comment]
Sure, the previous PR can provide a good example.  Also, the proc man page provides the details regarding the fields contained in meminfo.
http://man7.org/linux/man-pages/man5/proc.5.html
