### ISSUE TITLE
Is there a switch to disable log print ?

### ISSUE THREAD

**Issue by Jack-Kingdom** [prometheus/procfs#233]
`log.Println` be called on every reading, just like the below image shows, this cause so many logs writes to stderr.
Is there a switch to close log print ?

<img width="531" alt="Screen Shot 2019-11-14 at 11 05 38" src="https://user-images.githubusercontent.com/10584772/68823457-c49eea00-06ce-11ea-8508-cc12f81a2828.png">

**Comment by SuperQ** [comment]
Whups! That's a bug, a leftover from development debugging.
