### ISSUE TITLE
Add parsing of /proc/swaps

### ISSUE THREAD

**Issue by stevenjm** [prometheus/procfs#244]
I currently have a WIP implementation at https://github.com/usabilla/prometheus-procfs/tree/swap (with a corresponding WIP change to the node exporter at https://github.com/usabilla/prometheus-node_exporter/tree/swap), but both of these lack tests. Creating an issue to claim this task; I should be ready to raise a PR soon.

**Comment by discordianfish** [comment]
Great, thanks!

**Comment by pgier** [comment]
Fixed by #246
