### ISSUE TITLE
Feature - Watching Process Resources Changes

### ISSUE THREAD

**Issue by safwanolaimat** [prometheus/procfs#255]
Its good to have Feature Watching process Resources Allocation Changes

**Comment by discordianfish** [comment]
This is out of scope for this project. You can use Prometheus and https://github.com/prometheus/node_exporter to monitor resource usage etc.

**Comment by SuperQ** [comment]
For monitoring individual processes, there is the [process-exporter](https://github.com/ncabatoff/process-exporter).
