### ISSUE TITLE
Request: Expose hard limits as well

### ISSUE THREAD

**Issue by m0untains** [prometheus/procfs#28]
It would be useful to expose both soft and hard limits in proc_limits.go. I've run across a number of systems / processes where these values differ for "Max open files".

**Comment by brian-brazil** [comment]
It's not unusual for the limits to be different, it's the soft limit that applies though.

**Comment by grobie** [comment]
@or4cle What's your use case? As Brian said, the soft limit is the limit, the hard limit only specifies how far a normal user can increase the limit.

**Comment by pgier** [comment]
Closing this issue since there doesn't seem to be a use case currently for exposing the hard limits.  Feel free to reopen or create a new issue if there is a need for this.
