### ISSUE TITLE
debian packging warns source-contains-unsafe-symlink

### ISSUE THREAD

**Issue by sinzui** [prometheus/procfs#29]
A run of
    lintian -I --pedantic
across the package reveals
    E: juju-core source: source-contains-unsafe-symlink src/github.com/prometheus/procfs/fixtures/26231/exe

Anyone packaging this project needs to delete the fixtures directory, but then the tests cannot be run.

**Comment by grobie** [comment]
We could create the file on-the-fly, maybe during `make test`. I guess it'd make more sense to remove the test data from debian packages though.

**Comment by sinzui** [comment]
We did remove the fixtures directory from the source to make the package acceptable for Ubuntu. Now it isn't possible to run the tests. the ideal solution is for the test suite to create the symlink as needed.

**Comment by TheTincho** [comment]
@sinzui, actually, that file is correct there, and you need to add a lintian override.

having said that, there is no need to package this for ubuntu, it is been in debian for quite some time: https://packages.qa.debian.org/g/golang-procfs.html

**Comment by grobie** [comment]
Thanks @TheTincho. Closing this as I trust you in all questions around Debian packages.
