### ISSUE TITLE
No CPUInfo for all ARM

### ISSUE THREAD

**Issue by bluecmd** [prometheus/procfs#291]
Hi,

There has been changes in the CpuInfo part in the recent past, and e.g. https://github.com/prometheus/procfs/pull/290 adds some support for some ARM CPUs. However, that's only for v6.

Could we maybe enable parseCPUInfoARM for all ARM versions?

**Comment by discordianfish** [comment]
@bluecmd Makes sense, feel free to submit a PR to add all other ARM versions (assuming they have the same cpuinfo format)

**Comment by bluecmd** [comment]
Well, I can make sure to test it for a v5 ARM - but it seems unlikely to me that the format would be a function of the version of the instruction set. If there are ARM CPUs that have a separate format, likely they need to be handled by some other means than filtering by ARM version.

**Comment by discordianfish** [comment]
Yeah I think it's reasonable to enable this on all arm versions. If the format should be different, it will just return an error which isn't worse than have a compile error I guess.

**Comment by bluecmd** [comment]
So, it seems like what you have currently in tree is something quite special, ARM-wise.

Right now parseCPUInfoARM works for only a format that was [used 15 years ago](https://github.com/torvalds/linux/commit/1555972231f3202f00e04f7c42d2db858e11b874) and since then has been replaced with a format that looks like this:

```
/# cat /proc/cpuinfo 
processor	: 0
model name	: ARM926EJ-S rev 5 (v5l)
BogoMIPS	: 48.00
Features	: swp half thumb fastmult edsp java 
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 5

Hardware	: Generic DT based system
Revision	: 0000
Serial		: 0000000000000000
```

This new format is quite close to the x86 format, FWIW.

I can help fix this by looking at the kernel version and either error out, or parse the older format. And I will of course improve the tests.

Thoughts?

**Comment by discordianfish** [comment]
Uh.. hrm, that's unfortunate. @pgier thoughts?

**Comment by bluecmd** [comment]
My apologizes, I got the commit wrong - it seems this was changed [8 years ago in this commit](https://github.com/torvalds/linux/commit/b4b8f770eb10a1bccaf8aa0ec1956e2dd7ed1e0a). So from v3.8-rc1 and later.

**Comment by discordianfish** [comment]
It's close but not identical to x86 I assume?

**Comment by bluecmd** [comment]
Right, looking at x86 you're extracting many x86 specific attributes that ARM does not have, and likewise ARM has some things that x86 does not have - like "CPU architecture".

Do you wish to re-use this issue, or should we move to a new issue for upgrading the formatting for ARM?

**Comment by discordianfish** [comment]
New issue would make sense I think

**Comment by bluecmd** [comment]
Done, https://github.com/prometheus/procfs/issues/294
