### ISSUE TITLE
CPUInfo for ARM and Linux kernels newer than 3.8

### ISSUE THREAD

**Issue by bluecmd** [prometheus/procfs#294]
From #291 it was concluded that the current parsing code is limited to kernels [older than 3.8](https://github.com/torvalds/linux/commit/b4b8f770eb10a1bccaf8aa0ec1956e2dd7ed1e0a).

Problematic code is:
https://github.com/prometheus/procfs/blob/7a44272e0d68eea081a6f7e08430150a286eb734/cpuinfo.go#L189-L233

This code should be changed to either drop support for older kernels, or be capable of parsing both new and old kernels alike - probably with reduced functionality for the older ones.

**Comment by pgier** [comment]
I believe this is resolved now with the merge of #296
