### ISSUE TITLE
parseInfinibandDevice fails with Intel Omni-Path

### ISSUE THREAD

**Issue by ikirker** [prometheus/procfs#341]
It looks like [`parseInfinibandDevice`](https://github.com/prometheus/procfs/blob/c5c7bc5412c9e3a99be2ae1d89a3943e0836176e/sysfs/class_infiniband.go#L121) expects to see a file `/sys/class/infiniband/<Name>/hca_type` for each Infiniband device. (As well as `board_id` and `fw_ver`.)

Unfortunately, [this doesn't seem to be provided by the Omni-Path driver](https://github.com/torvalds/linux/blob/98913408c5465ac477f80da7affe347b413edaa4/Documentation/ABI/stable/sysfs-class-infiniband#L616), for some reason.

Downstream, this causes the node exporter to be unable to pick up Omni-Path devices with the Infiniband collector. (Which, I guess they're *strictly* not, but I think it's supposed to cover them as well.)

I'm not 100% sure what's supposed to come out of this file for other types of device: maybe the information from `board_id` is enough? Here's an example of the contents of that:

```
$ cat /sys/class/infiniband/hfi1_0/board_id
Intel Omni-Path Host Fabric Interface Adapter 100 Series
```

And there's also `hw_rev`:

```
$ cat /sys/class/infiniband/hfi1_0/hw_rev
11
```

Or would not producing an error if the `hca_type` file isn't found be appropriate?

**Comment by ikirker** [comment]
Okay, so, I pulled the snippet from the fixtures ttar, and I also realised we have a different system that has similar Mellanox cards in, so I got the equivalent from there, and then I grabbed the equivalent from our OmniPath system.


<details><summary>Excerpt from <code>fixtures.ttar</code></summary>
<pre><code># ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: fixtures/sys/class/infiniband/mlx4_0/board_id
Lines: 1
SM_1141000001000
Mode: 644
# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: fixtures/sys/class/infiniband/mlx4_0/fw_ver
Lines: 1
2.31.5050
Mode: 644
# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: fixtures/sys/class/infiniband/mlx4_0/hca_type
Lines: 1
MT4099
Mode: 644
</code></pre>
</details>

<details><summary>Equivalent snippet from one of our systems that also uses Mellanox cards</summary>
<pre><code># ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: infiniband/mlx5_0/board_id
Lines: 2
LNV0000000007
EOF
Mode: 444
# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: infiniband/mlx5_0/fw_ver
Lines: 2
16.26.1040
EOF
Mode: 444
# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: infiniband/mlx5_0/hca_type
Lines: 2
MT4119
EOF
Mode: 444
</code></pre></details>

<details><summary>And, again, the equivalent snippet from a system that uses OPA</summary>
<pre><code># ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: infiniband/hfi1_0/board_id
Lines: 2
HPE 100Gb 1-port OP101 QSFP28 x16 PCIe Gen3 with Intel Omni-Path Adapter
EOF
Mode: 444
# ttar - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Path: infiniband/hfi1_0/fw_ver
Lines: 2
1.27.0
EOF
Mode: 444
</code></pre>
</details>

So, the `board_id` files are quite different. Oh well, not anything I can change.

Reading some more of the Linux kernel documentation I linked above, it looks like providing `hca_type` is common but not universal, and isn't in the common interface list, so it seems right to not fail if it's not present. I guess that'll just leave the field with an empty string.

I'm happy to take this one on, if that's fine.

I'm not really sure how to deal with accounting for more extensive differences in the available metric sets in future, but that sounds like a more extensive piece of work.

**Comment by seb45tian** [comment]
@ikirker would you consider making a PR with your fix to this repo? Otherwise I think this will not be fixed any time soon.

**Comment by ikirker** [comment]
@seb45tian Ah, sorry, I made that naive fix, but making a test for it seemed surprisingly awkward, and then I realised I wasn't sure what to do with OmniPath adapters with respect to [this maybe-Mellanox-specific multiplier](https://github.com/prometheus/procfs/blob/master/sysfs/class_infiniband.go#L266).

And then I had to shelve it to handle a bunch of other work before I really got a chance to look at how to investigate that.

I'll see if I can make some tests work and commit them to my fork, and if so I'll PR it and some example ttar data. That'll at least give something to work with.

**Comment by ikirker** [comment]
@seb45tian I think this should fix it but I haven't done the node_exporter rebuild yet. (It's late. 😴)

Apart from the actual test in the PR, so far I've only tried it with a little stubby program that sets up the sysfs, detects all the IB devices, and dumps out the struct:

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/prometheus/procfs/sysfs"
)

func main() {
	var sysfsPath string
	if len(os.Args[1:]) > 0 {
		sysfsPath = os.Args[1]
	} else {
		sysfsPath = "/sys"
	}
	this_fs, err := sysfs.NewFS(sysfsPath)
	if err != nil {
		panic(err)
	}

	ib_devices, err := this_fs.InfiniBandClass()
	if err != nil {
		panic(err)
	}
	structJson, err := json.MarshalIndent(ib_devices, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(structJson))
}
```

**Comment by seb45tian** [comment]
@ikirker thank you for your efforts! I would definitely have failed at getting those tests work. I also rebuild the node_exporter with this fix and, for me, it works flawlessly!

I also looked into the whole [multiply by 4 issue](https://github.com/prometheus/procfs/blob/master/sysfs/class_infiniband.go#L266) and even though I could not find anything specific about how OmniPath treats this counter, I think this might be a *standard* for all infiniband drivers (c.f. [link](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband))? But I am by no means an expert on this.
