### ISSUE TITLE
unify error messages

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/procfs#358]
currently we have:

could not parse
failed to parse
error parsing
failed to read file ...
fail to scan

We should unify the error messages.

**Comment by alexal** [comment]
@roidelapluie I just created PR #360. Please check it out and let me know if I need to change something. Thanks.

**Comment by conallob** [comment]
Is PR #360 still ongoing or is it stalled? If there are no objections, I'm interested in taking this on

**Comment by SuperQ** [comment]
#360 is stalled, feel free to chery-pick and continue with it.

**Comment by conallob** [comment]
@SuperQ @discordianfish this was implemented in https://github.com/prometheus/procfs/pull/526

Could somebody assign this issue to me and mark it as closed please?
