### ISSUE TITLE
FreeBSD build error: undefined: syscall.ENODATA

### ISSUE THREAD

**Issue by rfratto** [prometheus/procfs#359]
#300 seems to have introduced a regression on FreeBSD:

```
vendor/github.com/prometheus/procfs/sysfs/class_thermal.go:51:22: undefined: syscall.ENODATA
```

You can see from the [Go source](https://golang.org/src/syscall/zerrors_freebsd_amd64.go) that ENODATA isn't an error on FreeBSD.

Unfortunately, I don't understand this enough myself to try to contribute a fix, but this is preventing me from building node_exporter for FreeBSD.

**Comment by SuperQ** [comment]
Hrm, that file should probably have a build tag to avoid being used on FreeBSD.

**Comment by rfratto** [comment]
Ah, that makes sense since thermal zones are only [used in Linux](https://github.com/prometheus/node_exporter/blob/306a3653779c13244b2dc72f5bdd6098a56f83ef/collector/thermal_zone_linux.go). It looks like sysfs is Linux specific, maybe all of these files should have `// +build linux` instead of `// +build !windows`?
