### ISSUE TITLE
Proposal: Make fixture archive / tree per package instead of global

### ISSUE THREAD

**Issue by jooola** [prometheus/procfs#368]
I propose to explode the single fixture archive / tree into multiple trees, in order to prevent collisions with other packages when updating the fixtures.

For instance, I was adding some fixtures for a new sysfs md array parser, but when adding a new `md0` device to `/sys/block/md0` the tests for the `blockdevice` failed.

Maybe we actually rely on having a single tree, to prevent creating duplicate files. Has this already been discussed ?

**Comment by discordianfish** [comment]
I don't really see a point in duplicating the fixtures. If we have a new collector that wants to test one edge case and another one test another edge case and therefor requiring the same files with different contents, we can revisit this. But I don't think there is a reason to change anything in advance.
