### ISSUE TITLE
Many files missing license header

### ISSUE THREAD

**Issue by mdlayher** [prometheus/procfs#37]
Just noticed this when @grobie asked me to put license headers on my XFS files in #36 .

We use a pretty rudimentary shell script check in go-qemu to verify each Go source file has a license.

https://github.com/digitalocean/go-qemu/blob/master/scripts/licensecheck.sh

 It would probably be a good idea to set up something similar in this repo, and other Prometheus repos.

**Comment by grobie** [comment]
See https://github.com/prometheus/prometheus/blob/master/scripts/check_license.sh as well. I guess we should open the discussion how/where to manage such scripts.
