### ISSUE TITLE
Why uid and gid in /proc/[pid]/status have been parsed as string?

### ISSUE THREAD

**Issue by MisLink** [prometheus/procfs#372]
As far as I know, they are uint32

**Comment by rexagod** [comment]
+1, I just verified this as well ([(1)](https://github.com/torvalds/linux/blob/8e938e39866920ddc266898e6ae1fffc5c8f51aa/include/linux/uidgid_types.h#L8), [(2)](https://github.com/torvalds/linux/blob/master/include/linux/types.h#L37-L38), and [(3)](https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/posix_types.h#L48-L51)), sending a patch!
