### ISSUE TITLE
Add support for parsing /proc/crypto

### ISSUE THREAD

**Issue by mdlayher** [prometheus/procfs#38]
This shows which cryptographic algorithms are available in the kernel, and which are being used.

```
$ head -n 9 /proc/crypto 
name         : crct10dif
driver       : crct10dif-pclmul
module       : crct10dif_pclmul
priority     : 200
refcnt       : 1
selftest     : passed
type         : shash
blocksize    : 1
digestsize   : 2

```

Seems like it'd probably be useful for some work I'm doing.  Maybe not as much in a metrics context, outside of the "reference count" field.

Feel free to assign to me.

**Comment by brian-brazil** [comment]
This doesn't seem like metrics data, it's getting more into fleet management.

**Comment by mdlayher** [comment]
> This procfs package provides functions to retrieve system, kernel and process metrics from the pseudo-filesystem proc.

Since the package description has no mention of metrics data, does that mean it is (or is not) okay to add functions that parse `/proc` files that don't provide useful metrics?

**Comment by brian-brazil** [comment]
That's fine in procfs currently, though if it gets to be a big burden we may need to split it out or something.
