### ISSUE TITLE
Any breaking changes since v0.1.3?

### ISSUE THREAD

**Issue by qdm12** [prometheus/procfs#389]
Hi there,

I'm on a quest to upgrade the dependency on this library in public repositories, usually from v0.1.3 to v0.3.0 (v0.6.0 ideally though), in order to support the riscv64 architecture (for example at https://github.com/golangci/golangci-lint/issues/2079).

Builds with the upgraded v0.6.0 library still work without issue, but we are wondering if you could tell us if you know any particular breaking behavioral change that occurred since then? Or you can point me to commits if you think they may be a breaking change and I can examine it.

Thank you!

**Comment by discordianfish** [comment]
We don't maintain a changelog for procfs unfortunately since the main intention of this library is being used in the node-exporter where we do maintain a changelog and we have limited resources.

**Comment by qdm12** [comment]
Makes sense. I'll dig in the release notes of node-exporter as well then, thanks. I might comment here with any breaking change I find.

Maybe keeping a changelog in the future would be nice, since it seems to be used a bit across key Go libraries out of Prometheus (kubernetes, helm, etc.).

Thanks !

**Comment by discordianfish** [comment]
@qdm12 Yeah we discussed that. I guess this issue was the reason for @SuperQ to bring it up? So yeah with people actively asking for it it probably makes sense to start a changelog.
