### ISSUE TITLE
read statistics in /proc/cgroups

### ISSUE THREAD

**Issue by biello** [prometheus/procfs#423]
In some case, people may want to monitor statistics in /proc/cgroups on linux systems, I have already written some code for it.
will it be useful? if yes, I would like to contribute a pr. Thanks! @discordianfish 

/enhancement

**Comment by discordianfish** [comment]
It depends on the details, but in general we support /proc/cgroups already: https://github.com/prometheus/procfs/blob/master/proc_cgroup.go

What do you have in mind?

**Comment by biello** [comment]
@discordianfish Current proc_cgroup.go reads /proc/[pid]/cgroup which describes infos for each process, not an overall view of control groups on the whole system. What I would like to read is the /proc/cgroups file, it contains relevant information.

[https://man7.org/linux/man-pages/man7/cgroups.7.html](https://man7.org/linux/man-pages/man7/cgroups.7.html) has a clear description about this file.

**Comment by discordianfish** [comment]
Ah I see, yeah that seems reasonable to me!

**Comment by biello** [comment]
Close this issue as https://github.com/prometheus/procfs/pull/424 is merged. 🍻
