### ISSUE TITLE
Introduce support for `/proc/<algod PID>/net/snmp` and `/proc/uptime`

### ISSUE THREAD

**Issue by nikakis** [prometheus/procfs#434]
Hello guys! 
Would you consider a PR for enhancing support for `/proc/<algod PID>/net/snmp` and `/proc/uptime`?
Thanks!!!

**Comment by SuperQ** [comment]
There's already `BootTime()` from `/proc/stat`, so `/proc/uptime` isn't as necessary.

Adding a parser for `net/snmp` would be useful. We currently have an old [parser in the node_exporter](https://github.com/prometheus/node_exporter/blob/master/collector/netstat_linux.go), It would be nice to migrate that to this codebase like we have been doing with other parsers.

**Comment by nikakis** [comment]
Ok great!!! 
I will do the migration @SuperQ. Is it possible to share with me a reference from a similar migration or give me a hint? Just to be sure that i will be in the right path.
Thanks!!!

**Comment by SuperQ** [comment]
Take a look at the PR history in this repo, there are lots of good examples.

**Comment by nikakis** [comment]
@SuperQ Please have a first look in the [PR](https://github.com/prometheus/procfs/pull/435)

**Comment by nikakis** [comment]
I think this issue can be closed as the implementation is done in this [PR](https://github.com/prometheus/procfs/pull/435)

**Comment by discordianfish** [comment]
Great!
