### ISSUE TITLE
ReadFileNoStat causes issues collecting mountinfo with high number of mounts

### ISSUE THREAD

**Issue by anguswilliams** [prometheus/procfs#457]
We have some unique hosts that have very high numbers of NFS mounts (1000+), which causes some issues with the 512kb limit imposed by ReadFileNoStat.

On some of the hosts, I have noticed errors like this cropping up, where the error shows a truncated mountinfo line.

```
couldn't find enough fields in mount string: 32184 30884 0:619 / /x ro,relatime shar
```

Inspecting `/proc/self/mountinfo` for this mount shows no error and the line looks fine and has 11 space separated elements.

Looking at the size of the mountinfo file in the proc structure, the server is sitting above the 512kb limit.

```
$ wc -c /proc/self/mountinfo
557896 /proc/self/mountinfo
```

It looks like mountinfo was changed from using `os.Open` to `util.ReadFileNoStat` in this merge request.
https://github.com/prometheus/procfs/pull/228/files

Would the correct approach here be to revert back to opening `/proc/self/mountinfo` with os.Open?

**Comment by SuperQ** [comment]
That is a lot of mounts.

* Go back to using a scanner.
* Make  `ReadFileNoStat` function have a configurable buffer size.
* Increase the default size to 1MiB.

Increasing the default max buffer size to 1MiB is probably the easiest thing to do.
