### ISSUE TITLE
GetRaplZones fails with zone names of the form package-N-die-M

### ISSUE THREAD

**Issue by tomhughes** [prometheus/procfs#459]
I have a machine which, since a recent kernel upgrade, has rapl zones with names like `package-0-die-0` and `package-0-die-3` which confuse `GetRaplZones` as the name parsing at https://github.com/prometheus/procfs/blob/4ba3093565a1a6c72b1a89a8234a67dc8c560177/sysfs/class_powercap.go#L102 tries to parse `0-die-0` as a number and fails, leading to the whole thing being returned as the name.

In turn that leads to node_collector crashing due an invalid metric name of `node_rapl_package-0-die-0_joules_total`.

**Comment by SuperQ** [comment]
This is actually a bug in the node_exporter, not the library.

https://github.com/prometheus/node_exporter/issues/2299

**Comment by tomhughes** [comment]
Ah apologies for that. I had actually started with the code when trying to figure this out but didn't realise it included unreleased fixes.
