### ISSUE TITLE
Add support for parsing /sys/class/thermal/

### ISSUE THREAD

**Issue by SuperQ** [prometheus/procfs#46]
Add support for parsing the generic thermal device tree[0] in `/sys/class/thermal/`.

[0]: https://www.kernel.org/doc/Documentation/thermal/sysfs-api.txt

**Comment by nilium** [comment]
I'll probably take a look at this tomorrow-ish (late right now) since it'll make it easier to monitor my ARM systems.

**Comment by HowToMeetLadies** [comment]
cat /sys/class/thermal/thermal_zone2/mode
**disabled**

journalctl -fu node_exporter
level=error caller=collector.go:161 msg="collector failed" name=thermal_zone duration_seconds=0.000795087 err="read /sys/class/thermal/thermal_zone2/temp: **invalid argument**"
