### ISSUE TITLE
go 1.15 compatibility?

### ISSUE THREAD

**Issue by baryluk** [prometheus/procfs#465]
Debian stable has go 1.15, but procfs uses few new library features:

```
go: downloading github.com/prometheus/procfs v0.8.0
# github.com/prometheus/procfs/internal/util
../../../../go/pkg/mod/github.com/prometheus/procfs@v0.8.0/internal/util/parse.go:69:15: undefined: os.ReadFile
../../../../go/pkg/mod/github.com/prometheus/procfs@v0.8.0/internal/util/parse.go:78:15: undefined: os.ReadFile
../../../../go/pkg/mod/github.com/prometheus/procfs@v0.8.0/internal/util/readfile.go:36:9: undefined: io.ReadAll
```

Right now `os.ReadFile` and `io.ReadAll` are just convenience functions, so can be reimplemented directly in readfile.go?. (There is proposed Linux syscall for ReadFile as one syscall, instead of open, read, close, but it is not merged yet into kernel).

There is already very similar `SysReadFile` in util.

**Comment by SuperQ** [comment]
Sorry, we dropped Go older than 1.17 for several Go API reasons. You can get Go 1.18 from bullseye-backports.

**Comment by baryluk** [comment]
You right, will use `bullseye-backports`. It works. Thanks.
