### ISSUE TITLE
Add support for `/sys/fs/cgroup/*` files

### ISSUE THREAD

**Issue by Dentrax** [prometheus/procfs#480]
procfs currently support `proc_cgroup` and `proc_cgroups` files but I'd like to get some useful information on `/sys/fs/cgroup/*` files:

```
$ ls /sys/fs/cgroup/

cgroup.controllers      cgroup.stat             cpu.stat               dev-mqueue.mount  io.pressure       memory.pressure                sys-fs-fuse-connections.mount  system.slice
cgroup.max.depth        cgroup.subtree_control  cpuset.cpus.effective  init.scope        io.prio.class     memory.stat                    sys-kernel-config.mount        user.slice
cgroup.max.descendants  cgroup.threads          cpuset.mems.effective  io.cost.model     io.stat           misc.capacity                  sys-kernel-debug.mount
cgroup.procs            cpu.pressure            dev-hugepages.mount    io.cost.qos       memory.numa_stat  proc-sys-fs-binfmt_misc.mount  sys-kernel-tracing.mount
```

Wdyt? Does it make sense?

**Comment by discordianfish** [comment]
We decided against supporting container metrics in the node-exporter and procfs. I'm open to revisit this though if there is a clear use case and we can ensure this is low effort to maintain. /cc @SuperQ

**Comment by SuperQ** [comment]
Are there any other cgroup parsing packages out there? This seems like something some other people have already solved.

**Comment by Dentrax** [comment]
Not 100% sure, but maybe `cAdvisor`? https://github.com/google/cadvisor/blob/master/container/libcontainer/helpers.go It uses runc implementation under the hood: https://github.com/opencontainers/runc/tree/main/libcontainer/cgroups

It'd be great to maintain a "very lightweight" implementation in procfs rather than having the dependency entirely.

**Comment by discordianfish** [comment]
Yeah I wouldn't make procfs depend on runc. The question is why people should use our procfs implementation instead of just using runc as e.g cadvisor does?

**Comment by Dentrax** [comment]
> The question is why people should use our procfs implementation instead of just using runc as e.g cadvisor does

That's because people also wouldn't make their project depend on runc or cAdvisor either. Since they have the lots of dependencies. As someone who need to parse and read `/sys/fs/cgroup/*` files, I'd rather have it in procfs instead.

**Comment by discordianfish** [comment]
Agreed with @SuperQ, would make sense to split out the cgroup parsing from runc into a separate lib. But to re-iterate, it might already be possible to use that without depending on other parts of runc.
Either way, going to close this for now
