### ISSUE TITLE
nfsd v4 ops index mismatch

### ISSUE THREAD

**Issue by atkinsam** [prometheus/procfs#492]
Hi, I believe the nfsd v4 ops parsing here uses indices which are mismatched on some ops. https://github.com/prometheus/procfs/blob/6efaedecce726b918b26265fdebc9548008f0e5b/nfs/parse.go#L269 

I can see that many/most are correct:
 - [access uses index 4](https://github.com/prometheus/procfs/blob/6efaedecce726b918b26265fdebc9548008f0e5b/nfs/parse.go#L279), which corresponds with [index 3 in the kernel](https://elixir.bootlin.com/linux/v5.10.162/source/include/linux/nfs4.h#L79) (the off-by-one appears to be due to the parser leaving the [LAST_NFS4_OP](https://elixir.bootlin.com/linux/v5.10.162/C/ident/LAST_NFS4_OP) value [in the array](https://github.com/prometheus/procfs/blob/6efaedecce726b918b26265fdebc9548008f0e5b/nfs/parse.go#L270)
 - [close uses index 5](https://github.com/prometheus/procfs/blob/6efaedecce726b918b26265fdebc9548008f0e5b/nfs/parse.go#L280), which corresponds with [index 4 in the kernel](https://elixir.bootlin.com/linux/v5.10.162/source/include/linux/nfs4.h#L80).

But the write operation, for example, appears to be incorrect. The [parser uses index 37](https://github.com/prometheus/procfs/blob/6efaedecce726b918b26265fdebc9548008f0e5b/nfs/parse.go#L312), but the write operation uses [index 38 in the kernel](https://elixir.bootlin.com/linux/v5.10.162/source/include/linux/nfs4.h#L114). So the parser should really be using index 39. 

I noticed this by comparing stats emitted by [node_exporter](https://github.com/prometheus/node_exporter) with what I see in `nfsstat -s`.

**Comment by discordianfish** [comment]
Thanks! Can you submit a PR to fix this?

**Comment by jjaakkol** [comment]
I can confirm that this pull request fixes the issue. My Grafana dashboard now correctly reports NFSv4 writes.
