### ISSUE TITLE
strings.TrimRight is used instead of TrimSuffix

### ISSUE THREAD

**Issue by GrosQuildu** [prometheus/procfs#507]
This line aims to remove " kB" suffix, but instead removes all characters from " kB" cutset. 
https://github.com/prometheus/procfs/blob/cdc45126aef95c2e741f1d56ded3d24fdcd3d167/proc_smaps.go#L130

Similar fix as was done in this commit is required - https://github.com/prometheus/procfs/commit/b3d77ecba8e7aeb7b4ff946644b1013199656c42 .

**Comment by discordianfish** [comment]
Oops, thanks! Wanna submit a quick PR to fix this?
