### ISSUE TITLE
Release v0.10.0 does not build with GOOS=windows + GOARCH=amd64

### ISSUE THREAD

**Issue by adrianosela** [prometheus/procfs#527]
## Release v0.10.0 does not build with GOOS=windows + GOARCH=amd64

Packages importing v0.10.0 of this module (github.com/prometheus/procfs) cannot build for amd64 windows.

Issue likely introduced via https://github.com/prometheus/procfs/commit/80824fa6b8fa49fbc0b58cf6a2271ec78777d595 and solved for certain operating systems via https://github.com/prometheus/procfs/pull/523 (but not windows!)

### Example

```
10:41 $ GOOS=windows GOARCH=amd64 go build .
# github.com/prometheus/procfs
../../../../pkg/mod/github.com/prometheus/procfs@v0.10.0/fs_statfs_type.go:25:18: undefined: syscall.Statfs_t
../../../../pkg/mod/github.com/prometheus/procfs@v0.10.0/fs_statfs_type.go:26:17: undefined: syscall.Statfs
```

Release v0.10.0 is a breaking change. Kindly look into this.

**Comment by SuperQ** [comment]
Released as https://github.com/prometheus/procfs/releases/tag/v0.10.1
