### ISSUE TITLE
Commit fdb70a7 breaks golang_client on Windows

### ISSUE THREAD

**Issue by qoke** [prometheus/procfs#53]
Commit fdb70a78745a8df006f953b8bab85597d96b2e0e breaks pulling master golang_client on Windows due to unsupported windows filenames in prometheus/procfs/sysfs/fixtures/devices/pci0000:00/0000:00:0d.0

I'm guessing its the colons ":" in the filenames, as the git error is:

```
$ go get -u github.com/prometheus/procfs
# cd C:\_MANUALLY_ELIDED_\src\github.com\prometheus\procfs; git pull --ff-only
From https://github.com/prometheus/procfs
   abf152e..a66a2f8  master     -> origin/master
 * [new branch]      superq/thermal -> origin/superq/thermal
Updating abf152e..a66a2f8
fatal: cannot create directory at 'sysfs/fixtures/devices/pci0000:00': Invalid argument
package github.com/prometheus/procfs: exit status 128
```

**Comment by grobie** [comment]
While you were the first to open the issue, there is already a discussion on #54. Closing as duplicate.
