### ISSUE TITLE
Codespell CI job is broken

### ISSUE THREAD

**Issue by mwasilew2** [prometheus/procfs#536]
As per: https://github.com/prometheus/procfs/pull/532#issuecomment-1592684982 , there was a new version of codespell pip package released on 14.06.2023 . CI for `prometheus/procfs` currently fails as a result. TBD if any other prometheus projects are impacted

**Comment by mwasilew2** [comment]
I found the following projects that are using codespell in their CI:
- https://github.com/prometheus/procfs (this project)
- https://github.com/prometheus/node_exporter
- https://github.com/prometheus/mysqld_exporter

A number of projects in the `prometheus-community`. Here are a few examples:
- https://github.com/prometheus-community/systemd_exporter
- https://github.com/prometheus-community/bind_exporter
- https://github.com/prometheus-community/windows_exporter
- https://github.com/prometheus-community/ipmi_exporter
- https://github.com/prometheus-community/smartctl_exporter

I'll focus on testing and fixing projects in `prometheus` and will see if I get a chance to look into the ones in the `prometheus-community`

**Comment by mwasilew2** [comment]
+1 on Ben's approach in: https://github.com/prometheus/procfs/pull/535

**Comment by SuperQ** [comment]
Yea, I think we used codespell in a few places that have non-go code. But I think we could mostly switch to golangci-lint.

**Comment by mwasilew2** [comment]
@SuperQ if #535 works as expected I'm happy to drive a similar change for `node_exporter` and `mysqld_exporter`

**Comment by mwasilew2** [comment]
@SuperQ I was looking at switching `node_exporter` to golangci-lint misspell and found out that the misspell project has been abandoned for at least 5 years. Do we even want to switch the other projects from codespell to misspell?
