### ISSUE TITLE
bcache folders breaks transtive imports to windows

### ISSUE THREAD

**Issue by twinj** [prometheus/procfs#54]
#51 The folders in the repo cannot be created on a windows machine when checking out the head. 

` git clone https://github.com/prometheus/procfs I:\tools\go\path\src\github.com\prometheus\procfs
Cloning into 'I:\tools\go\path\src\github.com\prometheus\procfs'...
fatal: cannot create directory at 'sysfs/fixtures/devices/pci0000:00': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

package github.com/prometheus/procfs: exit status 128`

I do not use your package directly  it is a transitive dependency from go-kit

**Comment by grobie** [comment]
@twinj I assume the colons in the filenames are the issue?

@ideaship Ugh, we need to find a solution. Any ideas? First things coming to my mind:

* package all fixtures in a tarball/zip/something and unpack before running tests (Makefile?). Makes diff very cumbersome
* Rename all fixture files removing characters invalid on Windows, rename before running tests
* Combine all fixture files in one text file of some format. Parse template and create actual files before running tests.

**Comment by twinj** [comment]
Aye. The colon.

And these too. `/ ? < > \ : * | "`

**Comment by grobie** [comment]
I won't be available until Monday, feel free to merge a solution @SuperQ @discordianfish @brian-brazil

**Comment by grobie** [comment]
Something like https://github.com/jtvaughan/ptar might be cool.

**Comment by ideaship** [comment]
@grobie ptar seems to be a rather exotic addition to the test requirements.

I don't see a good solution. I find renaming the fixture files just before running the tests the least bad of the bunch because the part that is annoying can be automated. We could simply replace colons with some other character (just in the directory tree where it is necessary), or have an additional files to map real names to Windows-consumable names.

By the way, will the symlinks result in errors on Windows, too?

**Comment by grobie** [comment]
Agreed in general. Tried a rename approach, but ran into issues as renames need to happen in the right order (colons are included in both directory names and file names) and I couldn't immediately come up with a solution working with standard tooling. As I'm running out of time and won't be available during the next days, I put together a quick fix in #55.

@ideaship More than happy to accept a nicer solution.

**Comment by grobie** [comment]
Fixed with a tarball quickfix. Open for better solutions @mdlayher @ideaship.

**Comment by ideaship** [comment]
@grobie Looks like the best quick fix. I'd take it.
