### ISSUE TITLE
No longer compiles on plan9

### ISSUE THREAD

**Issue by ncw** [prometheus/procfs#554]
This no longer compiles on plan9 which it used to.

This means that `"github.com/prometheus/client_golang/prometheus"` no longer compiles on plan9.

```
$ go get github.com/prometheus/procfs@master
$ GOOS=plan9 go build -v
github.com/prometheus/procfs
# github.com/prometheus/procfs
../../../../pkg/mod/github.com/prometheus/procfs@v0.11.1/fs_statfs_type.go:25:18: undefined: syscall.Statfs_t
../../../../pkg/mod/github.com/prometheus/procfs@v0.11.1/fs_statfs_type.go:26:17: undefined: syscall.Statfs
```

**Comment by discordianfish** [comment]
We need to move the types to a platform dependent file I guess.

**Comment by dswarbrick** [comment]
`fs_statfs_type.go` was initially checked in with build tags:
```
//go:build !netbsd && !openbsd && !solaris
```
and now has even more verbose tags:
```
//go:build !netbsd && !openbsd && !solaris && !windows && !nostatfs
```
`!plan9` could be added to these, but maybe it's more concise to specify the GOOS values which _do_ support `Statfs_t`.

**Comment by bozkayasalihx** [comment]
I had same issue too
