### ISSUE TITLE
open /proc/stat: too many open files

### ISSUE THREAD

**Issue by zkbaba** [prometheus/procfs#585]
hello, i encountered a problem: "open /proc/stat: too many open files". How can I solve it? Thank you.
code:
var cpuInfo, _ = procfs.NewFS(procfs.DefaultMountPoint)
stat1, err := cpuInfo.Stat()
if err != nil {
panic(err)
}

**Comment by BinSquare** [comment]
your system has a limit on number of files open at the same time. For linux, you can up your ulimit  https://ss64.com/bash/ulimit.html and/or identify if you have a leak via lsof https://www.redhat.com/sysadmin/analyze-processes-lsof

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
