### ISSUE TITLE
Limits that don't fit in an int32 aren't parsed, causing errors

### ISSUE THREAD

**Issue by ncabatoff** [prometheus/procfs#62]
In proc_limits, parseInt() uses strconv.ParseInt(s, 10, 32) to read limit values.  Some limit values won't fit in 32 bits, e.g. max file size, max address space.  As a result NewLimits() returns an error instead of the limits for the proc whenever one of those limits is too large.

**Comment by grobie** [comment]
Thanks for the report. Wanna give it a try in a PR?

**Comment by ncabatoff** [comment]
Sure.  Do you want me to make all members of ProcLimits be int64 for consistency, or only the ones we foresee as getting big enough to warrant it?

**Comment by SuperQ** [comment]
We should probably use int64 unless we know for sure that the data is int32.
