### ISSUE TITLE
Breaks docker-compose

### ISSUE THREAD

**Issue by Nighthawk22** [prometheus/procfs#75]
We are using the prometheus library at one of our projects and it seems like the fixtures directory is breaking the last docker-compose build:
```
> docker-compose up --build
Building offices
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 1001, in up
  File "compose/cli/main.py", line 997, in up
  File "compose/project.py", line 463, in up
  File "compose/service.py", line 310, in ensure_image_exists
  File "compose/service.py", line 989, in build
  File "site-packages/docker/api/build.py", line 150, in build
  File "site-packages/docker/utils/build.py", line 14, in tar
  File "site-packages/docker/utils/utils.py", line 103, in create_archive
IOError: Can not access file in context: /Users/someuser/projects/src/somerepo.net/repo/offices/vendor/github.com/prometheus/procfs/fixtures/26231/ns/mnt
Failed to execute script docker-compose
```
Building the service with docker itself is working prefectly fine.

Docker version:
```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:13:05 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	kubernetes

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:20:15 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

Docker-compose version:
```
docker-compose version 1.19.0, build 9e633ef
```

**Comment by codingconcepts** [comment]
Same issue here :(

**Comment by brian-brazil** [comment]
Have you filed a bug with docker-compose?

**Comment by codingconcepts** [comment]
From @Nighthawk22's message, it appears as though this was previously working with docker-compose.

Unfortunately, none of yesterday's checkins appear to have obviously broken anything...

**Comment by Nighthawk22** [comment]
Yes it was previously working. I will open a docker-compose ticket.

**Comment by codingconcepts** [comment]
Sorry if I'm being dense here but are you going to raise a ticket here https://github.com/docker/compose?

If so, isn't it more likely that this was working with the same version of docker-compose?

**Comment by Nighthawk22** [comment]
Nope definitly not. Also build a reproducable example.
Fails on every mac docker-compose with the same version:
https://github.com/Nighthawk22/procfs-test/

**Comment by codingconcepts** [comment]
I'm using docker-compose v2 at the moment and that's also broken.

**Comment by grobie** [comment]
Issue avoided by #79. Docker-compose should still not break if a package contains a symlink.
