### ISSUE TITLE
Error for NFS mounts via UDP

### ISSUE THREAD

**Issue by hakoerber** [prometheus/procfs#99]
I get the following error when using prometheus-node-exporter on a host that has NFS mounts via UDP:

```
failed to parse mountstats: invalid NFS transport stats 1.1 statement: [740 1 881477 875055 5946 2888414103 286261 16 258752 2080886]
```

I traced it back to the `xprt` field in `/proc/self/mountstats`, which has different fields depending on UDP/TCP, see also https://utcc.utoronto.ca/~cks/space/blog/linux/NFSMountstatsXprt

> For the udp RPC transport there is no connection count, connect idle time, or idle time (fields #3, #4, and #5); all other fields are the same. This omission of fields is quite annoying since it means you get to shuffle your code around instead of just ignoring certain fields for certain transports (they could perfectly well report the particular statistic as zero).

This means that https://github.com/prometheus/procfs/blob/7d6f385de8bea29190f15ba9931442a0eaef9af7/mountstats.go#L554 is only valid for TCP mounts.

I'd go ahead and try my luck at adding support for UDP mounts if you want. To keep the interface consistent, I would simply set the non-existent fields to 0 for UDP mounts.

Any objections?

**Comment by grobie** [comment]
Sounds great @hakoerber!

**Comment by SuperQ** [comment]
It would be good to have a way to identify TCP or UDP transport, we should add a field to the struct to indicate which fields are valid.

**Comment by grobie** [comment]
@SuperQ setting connection count and idle time to `0` doesn't strike me as "invalid" value for UDP? Having an attribute for the transport makes sense of course.

**Comment by SuperQ** [comment]
Yes, sorry, invalid is probably not the right word.  Maybe useful? :smile:

**Comment by hakoerber** [comment]
Thank you for your prompt responses!

How about the following:

I extend the `NFSTransportStats` struct with a `Protocol string` field that is either `tcp` or `udp`, like @SuperQ said. For TCP, nothing changes. For UDP, the TCP-only fields are simply set to zero.

How is backwards compatibility handled? In prometheus node exporter, we could use the Protocol as a label for the NFS metrics (and then maybe drop the TCP-only metrics for UDP)

P.S. I have to admit I just read CONTRIBUTING.md and saw that issues should be discussed in the mailing list. Should we move the discussion there?

**Comment by SuperQ** [comment]
When we integrate the procfs library vendor in the node_exporter, we can add the new label. It will have to wait for a new minor release as it's a breaking change.

**Comment by SuperQ** [comment]
This issue is fine for discussing the changes, as it's reasonably simple.

**Comment by hakoerber** [comment]
Ok, I will go ahead and make the changes, open a pull request and we can discuss it.

**Comment by hakoerber** [comment]
See #100 for the changes.
